/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ILogin;
import Controller.Login;
import Controller.Service;
import Model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class Form_ListUser extends javax.swing.JFrame {

    protected ILogin iLogin = new Login();
    private User _User = null;
    private DefaultTableModel model;
    private int indexClickTable = -2;
//    private Form_addUser form_addUser = null;
//    private Form_repairUser form_repairUser = null;

    /**
     * Creates new form User_control
     */
    public Form_ListUser() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    public Form_ListUser(User user) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        _User = user;
        setResizable(false);
        setLocationRelativeTo(this);
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
        };
        tbDanhSach.setModel(model);
        setCol();
        loadTable();
        btn_khoa.setEnabled(false);
        btn_sua.setEnabled(false);
        Thread th = new Thread() {
            public void run() {
                while (tbDanhSach.getRowCount() != 0) {
                    btn_khoa.setEnabled(true);
                    btn_sua.setEnabled(true);
                    break;
                }
            }
        };
        th.start();
    }

    private void setCol() {
        String[] arr = {"STT", "Tên đăng nhập", "Tên người dùng", "Trạng thái", "Chức vụ"};
        for (String x : arr) {
            model.addColumn(x);
        }
    }

    protected void loadTable() {
        model.setRowCount(0);
        int stt = 0;
        for (User x : iLogin.getListUser()) {
            if (!x.getUsername().equalsIgnoreCase(_User.getUsername())) {
                model.addRow(new Object[]{
                    ++stt, x.getUsername(), x.getName(),
                    x.isStatus() ? "Hoạt động" : "Khóa",
                    iLogin.getNameRole(x.getRole())
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_thoat = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_khoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tài khoản");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên tài khoản", "Tên người dùng", "Trạng thái", "Chức vụ"
            }
        ));
        tbDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDanhSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 461, 290));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("DANH SÁCH TÀI KHOẢN ĐĂNG NHẬP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 320, 30));

        btn_thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(255, 0, 51));
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 70, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Thêm tài khoản");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 130, 30));

        btn_khoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_khoa.setText("Khóa");
        btn_khoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_khoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 90, 30));

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sua.setText("Sửa tài khoản");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 130, 30));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 570, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Đóng cửa sổ quản lý tài khoản?", "Đóng",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (FormMain.form_addUser != null) {
                FormMain.form_addUser.setVisible(false);
            }
            if (FormMain.form_repairUser != null) {
                FormMain.form_repairUser.setVisible(false);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_khoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoaActionPerformed
        String inputUsername = "";
        if (indexClickTable == tbDanhSach.getSelectedRow()) {
            inputUsername = tbDanhSach.getValueAt(indexClickTable, 1).toString();
        } else {
            inputUsername = JOptionPane.showInputDialog("Nhập tài khoản đăng nhập muốn xóa!");
        }
        if (inputUsername == null || inputUsername.isEmpty()) {
            return;
        }
        if (inputUsername.equalsIgnoreCase(_User.getUsername())) {
            JOptionPane.showMessageDialog(this, "Không thể tự khóa tài khoản của bạn!");
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Đồng ý khoá người dùng " + inputUsername.toUpperCase(), "Khóa người dùng",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            User user = new User();
            user = iLogin.getUser(inputUsername);
            if (user != null) {
                user.setStatus(false);
                if (iLogin.editAccount(user)) {
                    JOptionPane.showMessageDialog(this, "Khóa thành công!");
                     Service._ILogin = new Login();
                    loadTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Khóa thất bại!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Người dùng không tồn tại!");
            }
        }
    }//GEN-LAST:event_btn_khoaActionPerformed

    private void tbDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachMouseClicked
        indexClickTable = tbDanhSach.getSelectedRow();
        if (evt.getClickCount() == 2) {
            String inputUserName = tbDanhSach.getValueAt(indexClickTable, 1).toString();
            new Form_repairUser(this, inputUserName).setVisible(true);
        }
    }//GEN-LAST:event_tbDanhSachMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        if (FormMain.form_repairUser != null) {
            FormMain.form_repairUser.dispose();
        }
        FormMain.form_repairUser = new Form_repairUser(this, _User);
        FormMain.form_repairUser.setVisible(true);
    }//GEN-LAST:event_btn_suaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (FormMain.form_addUser != null) {
            FormMain.form_addUser.dispose();
        }
        FormMain.form_addUser = new Form_addUser(this);
        FormMain.form_addUser.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_ListUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_khoa;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDanhSach;
    // End of variables declaration//GEN-END:variables
}
