/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.QuanLyHangNhap;
import Controller.QuanLyHangXuat;
import Controller.QuanLyTonKho;
import Controller.Service;
import Model.NhapHang;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author NgocPJa
 */
public class FormImportProduct extends javax.swing.JFrame {

    private List<NhapHang> lstAddProduct = new ArrayList<>();
    private NhapHang nhapHang;
    private FormMain _main = new FormMain();
    private DefaultTableModel model;
    private int idImport = 0;
    private int lotLo = 0; // lấy ra mã lô tự tăng
    private String dateAdd = "";
    private SimpleDateFormat _SimpleDateFormat;
    private Date _now = new Date();

    /**
     * Creates new form FormImport
     */
    public FormImportProduct() {
        setForm();
    }

    public FormImportProduct(FormMain main) {
        setForm();
        _main = main;
    }

    private void setForm() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }

        };
        tb_import.setModel(model);
        setCol();
        setCBCUnits();
        _SimpleDateFormat = new SimpleDateFormat("yyyy");
        setHanSD(_SimpleDateFormat.format(_now));
        _SimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateAdd = _SimpleDateFormat.format(_now);
        lblNgayNhap.setText(dateAdd);
        _SimpleDateFormat = new SimpleDateFormat("yyyyMMdd");
        lotLo = _main.iQuanLyHangnhap.getLotlo();
        lbl_malo.setText(_SimpleDateFormat.format(_now) + lotLo);
    }

    private void setHanSD(String year) {
        String[] thang = new String[12];
        for (int i = 0; i < thang.length; i++) {
            thang[i] = "" + (i + 1);
        }
        cbcThang.setModel(new DefaultComboBoxModel(thang));

        String[] ngay = new String[30];
        for (int i = 0; i < ngay.length; i++) {
            ngay[i] = "" + (i + 1);
        }
        cbcNgay.setModel(new DefaultComboBoxModel(ngay));

        String[] nam = new String[Integer.parseInt(year) + 10 - 1900];
        int nam1 = Integer.parseInt(year) + 10;
        for (int i = 0; i < nam.length; i++) {
            nam[i] = "" + (--nam1);
        }
        cbcNam.setModel(new DefaultComboBoxModel(nam));
        cbcNam.setSelectedItem(year);
    }

    private void setCol() {
        String[] arrCol = {"Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "Hạn sử dụng", "Vị trí", "Ghi chú", "Xóa"};
        for (String x : arrCol) {
            model.addColumn(x);
        }
    }

    private void setCBCUnits() {
        cbcDonVi.setModel(new DefaultComboBoxModel<>(_main.iQuanLyHangnhap.getNameUnits()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_big = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        lbl_malo = new javax.swing.JLabel();
        lbl_Title = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        cbcDonVi = new javax.swing.JComboBox<>();
        txt_vitri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbcNgay = new javax.swing.JComboBox<>();
        cbcThang = new javax.swing.JComboBox<>();
        cbcNam = new javax.swing.JComboBox<>();
        lblNgayNhap = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_import = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtGiaTien1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhập hàng");

        btn_them.setBackground(new java.awt.Color(51, 0, 255));
        btn_them.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btnNhap.setBackground(new java.awt.Color(51, 0, 255));
        btnNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnKetThuc.setBackground(new java.awt.Color(255, 0, 0));
        btnKetThuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Ghi chú:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Vị trí:");

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane1.setViewportView(txaGhiChu);

        lbl_malo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_malo.setText("Mã lô:");

        lbl_Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Title.setText("Nhập hàng");

        txtMaSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaSPKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Số lượng:");

        spinSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cbcDonVi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Giá tiền:");

        lblThanhTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Ngày hết hạn:");

        cbcNgay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcNgay.setForeground(new java.awt.Color(255, 0, 51));
        cbcNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01" }));
        cbcNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcNgayActionPerformed(evt);
            }
        });

        cbcThang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcThang.setForeground(new java.awt.Color(255, 0, 51));
        cbcThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01" }));
        cbcThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcThangActionPerformed(evt);
            }
        });

        cbcNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcNam.setForeground(new java.awt.Color(255, 0, 51));
        cbcNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020" }));
        cbcNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcNamActionPerformed(evt);
            }
        });

        lblNgayNhap.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNgayNhap.setForeground(new java.awt.Color(255, 0, 51));
        lblNgayNhap.setText("02-02-2020");

        tb_import.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã lô", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Thành tiền", "Người nhập", "Xóa"
            }
        ));
        tb_import.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_importMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_importMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tb_import);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mã lô:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Ngày nhập:");

        javax.swing.GroupLayout pn_bigLayout = new javax.swing.GroupLayout(pn_big);
        pn_big.setLayout(pn_bigLayout);
        pn_bigLayout.setHorizontalGroup(
            pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bigLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(lbl_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn_bigLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(lbl_malo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cbcDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtGiaTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(cbcNam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(cbcThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lblNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txt_vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(84, 84, 84)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pn_bigLayout.setVerticalGroup(
            pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bigLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_Title)
                .addGap(26, 26, 26)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7))
                            .addComponent(lbl_malo))
                        .addGap(8, 8, 8)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cbcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbcThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblNgayNhap))
                        .addGap(13, 13, 13)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13))
                            .addComponent(txt_vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_big, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_big, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        btnCancelAddProduct(this);
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        btnAddProductImport(this, txtMaSP, txtTenSP, spinSoLuong, cbcDonVi,
                txtGiaTien1, cbcNgay, cbcThang, cbcNam, txt_vitri, txaGhiChu, idImport);
    }//GEN-LAST:event_btn_themActionPerformed

    private void tb_importMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_importMousePressed
        btnDeleteRownTable(this, tb_import, evt);
    }//GEN-LAST:event_tb_importMousePressed

    private void txtMaSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSPKeyReleased
        String inputIdProduct = txtMaSP.getText();
        String nameProduct = _main.iQuanLyHangnhap.getNameProduct(inputIdProduct);
        if (nameProduct.isEmpty()) {
            for (NhapHang x : lstAddProduct) {
                if (x.getIdProduct().equalsIgnoreCase(inputIdProduct)) {
                    nameProduct = x.getNameProduct();
                    break;
                }
            }
        }
        if (nameProduct.isEmpty()) {
            txtTenSP.setText("");
            txtTenSP.setEditable(true);
        } else {
            txtTenSP.setText(nameProduct);
            txtTenSP.setEditable(false);
        }
    }//GEN-LAST:event_txtMaSPKeyReleased

    private void cbcThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcThangActionPerformed
        setHanSD();
    }//GEN-LAST:event_cbcThangActionPerformed

    private void cbcNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcNamActionPerformed
        setHanSD();
    }//GEN-LAST:event_cbcNamActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        btnImportProduct(this);
    }//GEN-LAST:event_btnNhapActionPerformed

    private void tb_importMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_importMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_importMouseClicked

    private void cbcNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcNgayActionPerformed

    // code chức năng nút nhập kho form nhập hàng
    private void btnAddProductImport(JFrame formAddProduct, JTextField txtIDProduct,
            JTextField txtNameProduct, JSpinner sprinAmount, JComboBox cbcUnit, JTextField txtPrice,
            JComboBox cbcDay, JComboBox cbcMonth, JComboBox cbcYear,
            JTextField txtLocation, JTextArea txaNote, int idImport) {
        StringBuilder sp = new StringBuilder();
        String idProduct = txtIDProduct.getText();
        String nameProduct = txtNameProduct.getText();
        Object values = sprinAmount.getValue();
        String amountProduct = values.toString();
        String unitProduct = (cbcUnit.getSelectedIndex() + 1) + "";
        String priceProduct = txtPrice.getText();
//        System.out.println(String.format("%02d", Integer.parseInt(cbcMonth.getSelectedItem() + "")));
        String expiryDateProduct = String.format("%04d", Integer.parseInt(cbcYear.getSelectedItem() + "")) + "-"
                + String.format("%02d", Integer.parseInt(cbcMonth.getSelectedItem() + "")) + "-"
                + String.format("%02d", Integer.parseInt(cbcDay.getSelectedItem() + ""));
        Date getExpiryDateProduct = null;
        try {
            getExpiryDateProduct = new SimpleDateFormat("yyyy-MM-dd").parse(expiryDateProduct);
        } catch (ParseException ex) {
            sp.append("Hạn sử dụng không đúng định dạng!\n");
        }
        String locationProduct = txtLocation.getText();
        String noteProduct = new String(txaNote.getText());
        if (idProduct.isEmpty()) {
            sp.append("Mã sản phẩm không được để trống!\n");
        } else {
            if (!idProduct.matches("[a-zA-Z0-9]+")) {
                sp.append("Mã sản phẩm không có ký tự đặc biệt hoặc dấu cách!\n");
            }
        }
        if (nameProduct.isEmpty()) {
            sp.append("Tên sản phẩm không được để trống!\n");
        } else {
            for (char x : nameProduct.toCharArray()) {
                if ((x + "").matches("\\p{Punct}")) {
                    sp.append("Tên sản phẩm không được có các ký tự đặc biệt!\n");
                    break;
                }
            }
        }
        if (amountProduct.isEmpty()) {
            sp.append("Số lượng sản phẩm không được để trống!\n");
        } else {
            if (!amountProduct.matches("[0-9]+")) {
                sp.append("Số lượng sản phẩm phải là một số nguyên dương!\n");
            } else {
                if (Integer.parseInt(amountProduct) < 1) {
                    sp.append("Số lượng sản phẩm phải >= 1 sản phẩm!\n");
                }
            }
        }
        if (priceProduct.isEmpty()) {
            sp.append("Giá của sản phẩm không được để trống!\n");
        } else {
            if (!priceProduct.matches("\\d+")) {
                sp.append("Giá của sản phẩm phải là một số nguyên dương hoặc một số thực!\n");
            } else {
                if (Double.parseDouble(priceProduct) < 0) {
                    sp.append("Giá của sản phẩm phải lớn hơn 0đ!\n");
                }
            }
        }
        if (locationProduct.isEmpty()) {
            sp.append("Vị trí của sản phẩm không được để trống!\n");
        }
        if (sp.length() == 0) {
            nhapHang = new NhapHang(lotLo, Double.parseDouble(priceProduct),
                    getExpiryDateProduct, _now, locationProduct,
                    noteProduct, idImport, idProduct, nameProduct,
                    Integer.parseInt(amountProduct), Integer.parseInt(unitProduct));
            for (NhapHang x : lstAddProduct) {
                _SimpleDateFormat = new SimpleDateFormat("yyyy-dd-MM hh:mm");
                if (nhapHang.getIdProduct().equalsIgnoreCase(x.getIdProduct())
                        && _SimpleDateFormat.format(nhapHang.getExpiryDate())
                                .equalsIgnoreCase(_SimpleDateFormat.format(x.getExpiryDate()))
                        && nhapHang.getLocation().equalsIgnoreCase(x.getLocation())
                        && nhapHang.getNameProduct().equalsIgnoreCase(x.getNameProduct())
                        && nhapHang.getPrice() == x.getPrice()
                        && nhapHang.getUnit() == x.getUnit()
                        && nhapHang.getNote().equalsIgnoreCase(x.getNote())) {
                    x.setAmount(x.getAmount() + nhapHang.getAmount());
                    nhapHang = null;
                    break;
                }
            }
            if (nhapHang != null) {
                lstAddProduct.add(nhapHang);

            }
//            JOptionPane.showMessageDialog(formAddProduct, "Thêm thành công ^^");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(formAddProduct, sp);
        }
    }

    // code chức năng nút hủy form nhập hàng
    private void btnCancelAddProduct(JFrame formAddProduct) {
        if (JOptionPane.showConfirmDialog(formAddProduct, "Hủy thêm sản phẩm?",
                "Thoát", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            formAddProduct.dispose();
        }
//        
//        if (lstAddProduct.isEmpty()) {
//            if (JOptionPane.showConfirmDialog(formAddProduct, "Hủy thêm sản phẩm?",
//                    "Thoát", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
//                formAddProduct.dispose();
//            }
//        } else {
//            if (JOptionPane.showConfirmDialog(formAddProduct,
//                    "Lưu lại danh sách sản phẩm trước khi đóng chương trình?",
//                    "Cảnh báo!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
//                if (_main.iQuanLyHangnhap.addProducts(lstAddProduct)) {
//                    JOptionPane.showMessageDialog(formAddProduct, "Lưu thành công!");
//                }
//            }
//            formAddProduct.dispose();
//        }F
    }

    // code chức năng nút nhập sản phẩm
    private void btnImportProduct(FormImportProduct formAddProduct) {
        if (JOptionPane.showConfirmDialog(formAddProduct,
                "Lưu lại danh sách sản phẩm?",
                "Cảnh báo!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (_main.iQuanLyHangnhap.addProducts(lstAddProduct)) {
                Service._IQuanLyHangNhap = new QuanLyHangNhap();
                Service._IQuanLyHangXuat = new QuanLyHangXuat();
                _main.iQuanLyTonKho = new QuanLyTonKho();
                _main.loadTableTonKho();
                _main.loadTableNhapHang();
                formAddProduct.dispose();
            }
        }
    }

    // code chức năng nút xóa một hàng của bảng form nhập hàng
    private void btnDeleteRownTable(JFrame formImport, JTable tbProduct, MouseEvent evt) {
        Point p = evt.getPoint();
        int row = tbProduct.rowAtPoint(p);
        int column = tbProduct.columnAtPoint(p);
        if (tbProduct.getValueAt(row, column).toString().equalsIgnoreCase("X")) {
            if (JOptionPane.showConfirmDialog(formImport,
                    "Đồng ý xóa sảng phẩm có mã SP " + tbProduct.getValueAt(row, 0).toString().toUpperCase(),
                    "Cảnh báo!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                lstAddProduct.remove(row);
                loadTable();
            }
        }
    }

    // code chức năng load dữ liệu lên table
    private void loadTable() {
        model.setRowCount(0);
        _SimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        for (NhapHang x : lstAddProduct) {
            model.addRow(new Object[]{
                x.getIdProduct(), x.getNameProduct(),
                x.getAmount() + " " + _main.iQuanLyHangnhap.getNameUnit(x.getUnit()),
                x.getPrice(), _SimpleDateFormat.format(x.getExpiryDate()), x.getLocation(), x.getNote(), "X"
            });
        }
    }

    private void setHanSD() {
        int indexNgay = cbcNgay.getSelectedIndex();
        switch ((String) cbcThang.getSelectedItem()) {
            case "1":
            case "3":
            case "5":
            case "7":
            case "8":
            case "10":
            case "12": {
                String[] ngay = new String[31];
                for (int i = 0; i < ngay.length; i++) {
                    ngay[i] = "" + (i + 1);
                }
                cbcNgay.setModel(new DefaultComboBoxModel(ngay));
                cbcNgay.setSelectedIndex(indexNgay);
            }
            break;
            case "4":
            case "6":
            case "9":
            case "11": {
                String[] ngay = new String[30];
                for (int i = 0; i < ngay.length; i++) {
                    ngay[i] = "" + (i + 1);
                }
                cbcNgay.setModel(new DefaultComboBoxModel(ngay));
                if (indexNgay >= 30) {
                    indexNgay = 0;
                }
                cbcNgay.setSelectedIndex(indexNgay);
            }
            break;
            case "2": {
                checkT2();
            }
            break;
        }
    }

    private void checkT2() {
        int indexNgay = cbcNgay.getSelectedIndex();
        int nam = Integer.parseInt((String) cbcNam.getSelectedItem());
        if (nam % 4 == 0 && nam % 100 != 0) {
            String[] ngay = new String[28];
            for (int i = 0; i < ngay.length; i++) {
                ngay[i] = "" + (i + 1);
            }
            cbcNgay.setModel(new DefaultComboBoxModel(ngay));
            if (indexNgay >= 28) {
                indexNgay = 0;
            }
            cbcNgay.setSelectedIndex(indexNgay);
        } else {
            String[] ngay = new String[29];
            for (int i = 0; i < ngay.length; i++) {
                ngay[i] = "" + (i + 1);
            }
            cbcNgay.setModel(new DefaultComboBoxModel(ngay));
            if (indexNgay >= 29) {
                indexNgay = 0;
            }
            cbcNgay.setSelectedIndex(indexNgay);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormImportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormImportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormImportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormImportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormImportProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cbcDonVi;
    private javax.swing.JComboBox<String> cbcNam;
    private javax.swing.JComboBox<String> cbcNgay;
    private javax.swing.JComboBox<String> cbcThang;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_malo;
    private javax.swing.JPanel pn_big;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tb_import;
    private javax.swing.JTextArea txaGhiChu;
    private javax.swing.JTextField txtGiaTien1;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txt_vitri;
    // End of variables declaration//GEN-END:variables
}
