package View;

import Controller.QuanLyHangNhap;
import Controller.QuanLyHangXuat;
import Controller.QuanLyTonKho;
import Controller.Service;
import Model.NhapHang;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dell
 */
public class FormEditProduct extends javax.swing.JFrame {

    private FormMain _main = new FormMain();
    private String _inputLoLo = null;
    private List<NhapHang> _getListByLotLo = new ArrayList<>();
    private String[] _arrCbcIdProduct = null;
    private NhapHang _nhapHang = null;
    private String date = null;
    private String day = null;
    private String month = null;
    private String year = null;
    private String dateNow = null;
    private int indexClickCbcIdProduct = -2;
    private SimpleDateFormat _SimpleDateFormat;
    private Date _now = new Date();

    /**
     * Creates new form sua
     */
    public FormEditProduct() {
        initComponents();
    }

    // truyền vào
    public FormEditProduct(FormMain main, String inputLotLo) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        _main = main;
        _inputLoLo = inputLotLo;
        this.setTitle("Sửa sản phẩm trong lô " + inputLotLo);
        lbl_Title.setText("Sửa sản phẩm lô " + inputLotLo);
        setLocationRelativeTo(this);
        setResizable(false);
        setForm();
    }

    private void setForm() {
        _getListByLotLo = _main.iQuanLyHangnhap.searchList(3, _inputLoLo);
        _arrCbcIdProduct = new String[_getListByLotLo.size()];
        for (int i = 0; i < _getListByLotLo.size(); i++) {
            _arrCbcIdProduct[i] = _getListByLotLo.get(i).getIdProduct();
        }
        _SimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        dateNow = _SimpleDateFormat.format(_now);
        setCbc(dateNow.substring(0, 4));
        lblNgaySua.setText(dateNow);
        lblLotlo.setText(_inputLoLo);
        if (!_getListByLotLo.isEmpty()) {
            getProductByIdProduct(0);
        }
    }

    // truyền vào năm hiện tại
    private void setCbc(String year) {
        // set cbc mã sản phẩm
        cbcMaSP.setModel(new DefaultComboBoxModel<>(_arrCbcIdProduct));

        // set cbc tháng
        String[] thang = new String[12];
        for (int i = 0; i < thang.length; i++) {
            thang[i] = "" + (i + 1);
        }
        cbcThang.setModel(new DefaultComboBoxModel(thang));

        // setcbc ngày
        String[] ngay = new String[30];
        for (int i = 0; i < ngay.length; i++) {
            ngay[i] = "" + (i + 1);
        }
        cbcNgay.setModel(new DefaultComboBoxModel(ngay));

        // set cbc năm
        String[] nam = new String[Integer.parseInt(year) + 10 - 1900];
        int nam1 = Integer.parseInt(year) + 10;
        for (int i = 0; i < nam.length; i++) {
            nam[i] = "" + (--nam1);
        }
        cbcNam.setModel(new DefaultComboBoxModel(nam));
        cbcNam.setSelectedItem(year);

        //set cbc Đơn vị
        cbcDonVi.setModel(new DefaultComboBoxModel<>(_main.iQuanLyHangnhap.getNameUnits()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_big = new javax.swing.JPanel();
        txtTenSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblNgaySua = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        cbcMaSP = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbcNgay = new javax.swing.JComboBox<>();
        lbl_Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtViTri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        cbcDonVi = new javax.swing.JComboBox<>();
        cbcThang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbcNam = new javax.swing.JComboBox<>();
        lblLotlo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Phân kho:");

        lblNgaySua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNgaySua.setForeground(new java.awt.Color(255, 0, 51));
        lblNgaySua.setText("02-02-2020");

        btnSua.setBackground(new java.awt.Color(51, 0, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        cbcMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbcMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcMaSPActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Ngày hết hạn:");

        cbcNgay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcNgay.setForeground(new java.awt.Color(255, 0, 51));
        cbcNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01" }));
        cbcNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcNgayActionPerformed(evt);
            }
        });

        lbl_Title.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Sửa hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Số lượng:");

        spinSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cbcDonVi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcDonVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tấn", "tạ", "cân", "gam" }));

        cbcThang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcThang.setForeground(new java.awt.Color(255, 0, 51));
        cbcThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01" }));
        cbcThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcThangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Giá tiền:");

        cbcNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcNam.setForeground(new java.awt.Color(255, 0, 51));
        cbcNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020" }));
        cbcNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcNamActionPerformed(evt);
            }
        });

        lblLotlo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLotlo.setText("lô 01");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Số lô:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Ngày sửa:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Ghi chú:");

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane1.setViewportView(txaGhiChu);

        javax.swing.GroupLayout pn_bigLayout = new javax.swing.GroupLayout(pn_big);
        pn_big.setLayout(pn_bigLayout);
        pn_bigLayout.setHorizontalGroup(
            pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bigLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(90, 90, 90)
                        .addComponent(lblLotlo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(cbcMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54)
                        .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cbcDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(64, 64, 64)
                        .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(cbcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(cbcNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbcThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(49, 49, 49)
                        .addComponent(lblNgaySua))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47)
                        .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_bigLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_bigLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_bigLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_bigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_bigLayout.setVerticalGroup(
            pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bigLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_Title)
                .addGap(16, 16, 16)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblLotlo))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbcMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lblNgaySua))
                .addGap(8, 8, 8)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pn_bigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnThoat))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_big, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_big, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbcNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcNgayActionPerformed

    private void cbcThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcThangActionPerformed
        setHanSD();
    }//GEN-LAST:event_cbcThangActionPerformed

    private void cbcNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcNamActionPerformed
        setHanSD();
    }//GEN-LAST:event_cbcNamActionPerformed

    private void cbcMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcMaSPActionPerformed
        indexClickCbcIdProduct = cbcMaSP.getSelectedIndex();
        if (indexClickCbcIdProduct > -1) {
            getProductByIdProduct(indexClickCbcIdProduct);
        }
    }//GEN-LAST:event_cbcMaSPActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Đồng ý thoát màn hình sửa sản phẩm?", "Thoát",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        btnEditProduct(cbcMaSP, txtTenSP, spinSoLuong, cbcDonVi, txtGiaTien, cbcNgay, cbcThang, cbcNam, txtViTri);
    }//GEN-LAST:event_btnSuaActionPerformed

    // code chức năng btn nút sửa form sửa sản phẩm
    private void btnEditProduct(JComboBox cbcIdProduct, JTextField txtNameProduct, JSpinner spinAmount,
            JComboBox cbcUnits, JTextField txtPrice, JComboBox cbcDay, JComboBox cbcMonth, JComboBox cbcYear,
            JTextField txtLocation) {
        StringBuilder sp = new StringBuilder();
        String getIDProduct = cbcIdProduct.getSelectedItem().toString();
        String getNameProduct = txtNameProduct.getText();
        Object values = spinAmount.getValue();
        String getAmountProduct = values.toString();
        String getUnitProduct = (cbcUnits.getSelectedIndex() + 1) + "";
        String getPrice = txtPrice.getText();
        String expiryDateProduct = String.format("%04d", Integer.parseInt(cbcYear.getSelectedItem() + "")) + "-"
                + String.format("%02d", Integer.parseInt(cbcMonth.getSelectedItem() + "")) + "-"
                + String.format("%02d", Integer.parseInt(cbcDay.getSelectedItem() + ""));
        Date getExpiryDateProduct = null;
        try {
            getExpiryDateProduct = new SimpleDateFormat("yyyy-MM-dd").parse(expiryDateProduct);
        } catch (ParseException ex) {
            sp.append("Hạn sử dụng không đúng định dạng!\n");
        }
        String getLocation = txtLocation.getText();
        if (getNameProduct.isEmpty()) {
            sp.append("Tên sản phẩm không được để trống!\n");
        } else {
            for (char x : getNameProduct.toCharArray()) {
                if ((x + "").matches("\\p{Punct}")) {
                    sp.append("Tên sản phẩm không được có các ký tự đặc biệt!\n");
                    break;
                }
            }
        }
        if (getAmountProduct.isEmpty()) {
            sp.append("Số lượng sản phẩm không được để trống!\n");
        } else {
            if (!getAmountProduct.matches("[0-9]+")) {
                sp.append("Số lượng sản phẩm phải là một số nguyên dương!\n");
            } else {
                if (Integer.parseInt(getAmountProduct) < 1) {
                    sp.append("Số lượng sản phẩm phải >= 1 sản phẩm!\n");
                } else {
                    if (Integer.parseInt(getAmountProduct) < _nhapHang.getAmountProductExport()) {
                        sp.append("Số lượng không được nhỏ hơn số lượng đã xuất!\n");
                    }
                }
            }
        }
        if (getPrice.isEmpty()) {
            sp.append("Giá của sản phẩm không được để trống!\n");
        } else {
            if (!getPrice.matches("[0-9]+\\.*[0-9]*")) {
                sp.append("Giá của sản phẩm phải là một số nguyên dương hoặc một số thực!\n");
            } else {
                try {
                    double price = Double.parseDouble(getPrice);
                    if (price <= 0) {
                        sp.append("Giá của sản phẩm phải lớn hơn 0đ!\n");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    sp.append("Giá tiền không đúng định dạng!");
                }
            }
        }
        if (getLocation.isEmpty()) {
            sp.append("Vị trí của sản phẩm không được để trống!\n");
        }
        if (sp.length() == 0) {
            if (_nhapHang.getIdProduct().equalsIgnoreCase(getIDProduct)) {
                _nhapHang.setNameProduct(getNameProduct);
                _nhapHang.setAmount(Integer.parseInt(getAmountProduct));
                _nhapHang.setUnit(Integer.parseInt(getUnitProduct));
                _nhapHang.setPrice(Double.parseDouble(getPrice));
                _nhapHang.setExpiryDate(getExpiryDateProduct);
                _nhapHang.setLocation(getLocation);
                _nhapHang.setNote(txaGhiChu.getText());
                if (_main.iQuanLyHangnhap.editProduct(_nhapHang)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công!");
                    Service._IQuanLyHangNhap = new QuanLyHangNhap();
                    Service._IQuanLyHangXuat = new QuanLyHangXuat();
                    _main.iQuanLyTonKho = new QuanLyTonKho();
                    _main.loadTableTonKho();
                    _main.loadTableNhapHang();
                    _main.loadTableXuatHang();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Dường như bạn đang cố làm cho chương trình chạy sai!");
            }
        } else {
            JOptionPane.showMessageDialog(this, sp);
        }
    }

    // set thông tin sản phẩm lên form
    private void getProductByIdProduct(int index) {
        _nhapHang = new NhapHang();
        _nhapHang = _getListByLotLo.get(index);
        txtTenSP.setText(_nhapHang.getNameProduct());
        spinSoLuong.setValue(_nhapHang.getAmount());
        cbcDonVi.setSelectedItem(_main.iQuanLyHangnhap.getNameUnit(_nhapHang.getUnit()));
        txtGiaTien.setText(_nhapHang.getPrice() + "");
        txtViTri.setText(_nhapHang.getLocation());
        _SimpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        date = _SimpleDateFormat.format(_nhapHang.getExpiryDate());
        day = date.substring(date.lastIndexOf("-") + 1, date.lastIndexOf("-") + 3);
        month = date.substring(date.indexOf("-") + 1, date.lastIndexOf("-"));
        year = date.substring(0, 4);
        cbcNgay.setSelectedItem(day);
        cbcThang.setSelectedItem(month);
        cbcNam.setSelectedItem(year);
        txaGhiChu.setText(_nhapHang.getNote());
    }

    // hàm set ngày theo tháng theo năm
    private void setHanSD() {
        int indexNgay = cbcNgay.getSelectedIndex();
        switch ((String) cbcThang.getSelectedItem()) {
            case "1":
            case "3":
            case "5":
            case "7":
            case "8":
            case "10":
            case "12": {
                String[] ngay = new String[31];
                for (int i = 0; i < ngay.length; i++) {
                    ngay[i] = "" + (i + 1);
                }
                cbcNgay.setModel(new DefaultComboBoxModel(ngay));
                cbcNgay.setSelectedIndex(indexNgay);
            }
            break;
            case "4":
            case "6":
            case "9":
            case "11": {
                String[] ngay = new String[30];
                for (int i = 0; i < ngay.length; i++) {
                    ngay[i] = "" + (i + 1);
                }
                cbcNgay.setModel(new DefaultComboBoxModel(ngay));
                if (indexNgay >= 30) {
                    indexNgay = 0;
                }
                cbcNgay.setSelectedIndex(indexNgay);
            }
            break;
            case "2": {
                checkT2();
            }
            break;
        }
    }

    // hàm thay đổi cbc ngày theo từng năm của tháng 2
    private void checkT2() {
        int indexNgay = cbcNgay.getSelectedIndex();
        int nam = Integer.parseInt((String) cbcNam.getSelectedItem());
        if (nam % 4 == 0 && nam % 100 != 0) {
            String[] ngay = new String[28];
            for (int i = 0; i < ngay.length; i++) {
                ngay[i] = "" + (i + 1);
            }
            cbcNgay.setModel(new DefaultComboBoxModel(ngay));
            if (indexNgay >= 28) {
                indexNgay = 0;
            }
            cbcNgay.setSelectedIndex(indexNgay);
        } else {
            String[] ngay = new String[29];
            for (int i = 0; i < ngay.length; i++) {
                ngay[i] = "" + (i + 1);
            }
            cbcNgay.setModel(new DefaultComboBoxModel(ngay));
            if (indexNgay >= 29) {
                indexNgay = 0;
            }
            cbcNgay.setSelectedIndex(indexNgay);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbcDonVi;
    private javax.swing.JComboBox<String> cbcMaSP;
    private javax.swing.JComboBox<String> cbcNam;
    private javax.swing.JComboBox<String> cbcNgay;
    private javax.swing.JComboBox<String> cbcThang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLotlo;
    private javax.swing.JLabel lblNgaySua;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel pn_big;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTextArea txaGhiChu;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
